server:
  port: 8080
spring:
  application:
    name: zuul

zuul:
  routes:
    app:
      path: /api/v1/demo/get
      url: http://localhost:8763
#      serviceId: client
      ##      sensitiveHeaders:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    ROOT: info
    org.springframework.web: info

ribbon:
  ReadTimeout: 6000000
  SocketTimeout: 6000000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000